# title: "Hypothesis testing (pooled interval, var1 = var2)"
# output: point estimate, confidence interval, margin of error, hypothesis testing and conclusion
#refer to Hypothesis testing using r data 1.txt


#Assume normal distributions with two equal variances for the Case Study in chapter
#6. For the given data set,

#reading data
eg = read.table("C:/Users/manga/OneDrive/Desktop/CA.txt", header = TRUE)

#verifying data
summary(eg)
boxplot(eg)
#1. Find the estimation for the difference of population means (µ1 ??? µ2), where µ1 is for control, µ2 for oil spill.

#(a) Point estimate.

pe = mean(eg$Control) - mean(eg$OilSpill)
pe

#ANS: 12.75


#(b) 96% confidence interval.


##i. Critical value t??/2.
cv <- qt(0.02, 78)
cv

##ANS: CV = -2.088663


##ii. Margin of Error.

n1 <- length(df$control)
n2 <- length(df$oil_spill)
s1 <- sd(df$control)
s2 <- sd(df$oil_spill)
sp <- sqrt(((n1 - 1) * s1^2 + (n2 - 1) * s2^2) / (n1 + n2 - 2))
se <- sqrt(sp^2 * (1/n1 + 1/n2))
me <- cv* se
me
#Ans: -5.201738

#iii. Confidence Interval.

conf_int <- c(pe- me, pe + me)
conf_int
# ANS: 17.951738  7.548262



#2. Find out if there is enough evidence to support hypothesis that µ1 is larger than µ2 by 10 units, given ?? = 0.05.

#(a) Set up hypotheses (H0 & H1) and tell the type of test.

#  Ho : mu1 <= mu2
#  Ha: mu1 > mu2


#(b) Calculate the observed Test Statistics t
t_stat <- (mean(df$control) - mean(df$oil_spill) - 10) / se
t_stat

#ANS:1.104213

.
#(c) Find the p-value of the test.
p_value <- pt(t_stat, 78, lower.tail = FALSE)
p_value
# ANS: 0.1364479


#(d) Draw your conclusion.

# Since the P-value > level of significance (alpha = 0.05), we can conclude that the mean of control is larger than that of the oil spill.

